# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gavinhulvey/Documents/GitHub/mipscript

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gavinhulvey/Documents/GitHub/mipscript

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gavinhulvey/Documents/GitHub/mipscript/CMakeFiles /Users/gavinhulvey/Documents/GitHub/mipscript//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gavinhulvey/Documents/GitHub/mipscript/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SyntaxTree

# Build rule for target.
SyntaxTree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SyntaxTree
.PHONY : SyntaxTree

# fast build rule for target.
SyntaxTree/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SyntaxTree.dir/build.make CMakeFiles/SyntaxTree.dir/build
.PHONY : SyntaxTree/fast

#=============================================================================
# Target rules for targets named Parser

# Build rule for target.
Parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Parser
.PHONY : Parser

# fast build rule for target.
Parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Parser.dir/build.make CMakeFiles/Parser.dir/build
.PHONY : Parser/fast

#=============================================================================
# Target rules for targets named MipScript

# Build rule for target.
MipScript: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MipScript
.PHONY : MipScript

# fast build rule for target.
MipScript/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MipScript.dir/build.make CMakeFiles/MipScript.dir/build
.PHONY : MipScript/fast

#=============================================================================
# Target rules for targets named IntegerParsingTest

# Build rule for target.
IntegerParsingTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IntegerParsingTest
.PHONY : IntegerParsingTest

# fast build rule for target.
IntegerParsingTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IntegerParsingTest.dir/build.make CMakeFiles/IntegerParsingTest.dir/build
.PHONY : IntegerParsingTest/fast

#=============================================================================
# Target rules for targets named WhitespaceParsingTest

# Build rule for target.
WhitespaceParsingTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WhitespaceParsingTest
.PHONY : WhitespaceParsingTest

# fast build rule for target.
WhitespaceParsingTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhitespaceParsingTest.dir/build.make CMakeFiles/WhitespaceParsingTest.dir/build
.PHONY : WhitespaceParsingTest/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MipScript.dir/build.make CMakeFiles/MipScript.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MipScript.dir/build.make CMakeFiles/MipScript.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MipScript.dir/build.make CMakeFiles/MipScript.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser/Parser.o: src/parser/Parser.cpp.o
.PHONY : src/parser/Parser.o

# target to build an object file
src/parser/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Parser.dir/build.make CMakeFiles/Parser.dir/src/parser/Parser.cpp.o
.PHONY : src/parser/Parser.cpp.o

src/parser/Parser.i: src/parser/Parser.cpp.i
.PHONY : src/parser/Parser.i

# target to preprocess a source file
src/parser/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Parser.dir/build.make CMakeFiles/Parser.dir/src/parser/Parser.cpp.i
.PHONY : src/parser/Parser.cpp.i

src/parser/Parser.s: src/parser/Parser.cpp.s
.PHONY : src/parser/Parser.s

# target to generate assembly for a file
src/parser/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Parser.dir/build.make CMakeFiles/Parser.dir/src/parser/Parser.cpp.s
.PHONY : src/parser/Parser.cpp.s

src/parser/SyntaxNode.o: src/parser/SyntaxNode.cpp.o
.PHONY : src/parser/SyntaxNode.o

# target to build an object file
src/parser/SyntaxNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SyntaxTree.dir/build.make CMakeFiles/SyntaxTree.dir/src/parser/SyntaxNode.cpp.o
.PHONY : src/parser/SyntaxNode.cpp.o

src/parser/SyntaxNode.i: src/parser/SyntaxNode.cpp.i
.PHONY : src/parser/SyntaxNode.i

# target to preprocess a source file
src/parser/SyntaxNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SyntaxTree.dir/build.make CMakeFiles/SyntaxTree.dir/src/parser/SyntaxNode.cpp.i
.PHONY : src/parser/SyntaxNode.cpp.i

src/parser/SyntaxNode.s: src/parser/SyntaxNode.cpp.s
.PHONY : src/parser/SyntaxNode.s

# target to generate assembly for a file
src/parser/SyntaxNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SyntaxTree.dir/build.make CMakeFiles/SyntaxTree.dir/src/parser/SyntaxNode.cpp.s
.PHONY : src/parser/SyntaxNode.cpp.s

src/parser/SyntaxTree.o: src/parser/SyntaxTree.cpp.o
.PHONY : src/parser/SyntaxTree.o

# target to build an object file
src/parser/SyntaxTree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SyntaxTree.dir/build.make CMakeFiles/SyntaxTree.dir/src/parser/SyntaxTree.cpp.o
.PHONY : src/parser/SyntaxTree.cpp.o

src/parser/SyntaxTree.i: src/parser/SyntaxTree.cpp.i
.PHONY : src/parser/SyntaxTree.i

# target to preprocess a source file
src/parser/SyntaxTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SyntaxTree.dir/build.make CMakeFiles/SyntaxTree.dir/src/parser/SyntaxTree.cpp.i
.PHONY : src/parser/SyntaxTree.cpp.i

src/parser/SyntaxTree.s: src/parser/SyntaxTree.cpp.s
.PHONY : src/parser/SyntaxTree.s

# target to generate assembly for a file
src/parser/SyntaxTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SyntaxTree.dir/build.make CMakeFiles/SyntaxTree.dir/src/parser/SyntaxTree.cpp.s
.PHONY : src/parser/SyntaxTree.cpp.s

tests/parsing/test_integers.o: tests/parsing/test_integers.cpp.o
.PHONY : tests/parsing/test_integers.o

# target to build an object file
tests/parsing/test_integers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IntegerParsingTest.dir/build.make CMakeFiles/IntegerParsingTest.dir/tests/parsing/test_integers.cpp.o
.PHONY : tests/parsing/test_integers.cpp.o

tests/parsing/test_integers.i: tests/parsing/test_integers.cpp.i
.PHONY : tests/parsing/test_integers.i

# target to preprocess a source file
tests/parsing/test_integers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IntegerParsingTest.dir/build.make CMakeFiles/IntegerParsingTest.dir/tests/parsing/test_integers.cpp.i
.PHONY : tests/parsing/test_integers.cpp.i

tests/parsing/test_integers.s: tests/parsing/test_integers.cpp.s
.PHONY : tests/parsing/test_integers.s

# target to generate assembly for a file
tests/parsing/test_integers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IntegerParsingTest.dir/build.make CMakeFiles/IntegerParsingTest.dir/tests/parsing/test_integers.cpp.s
.PHONY : tests/parsing/test_integers.cpp.s

tests/parsing/test_whitespace.o: tests/parsing/test_whitespace.cpp.o
.PHONY : tests/parsing/test_whitespace.o

# target to build an object file
tests/parsing/test_whitespace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhitespaceParsingTest.dir/build.make CMakeFiles/WhitespaceParsingTest.dir/tests/parsing/test_whitespace.cpp.o
.PHONY : tests/parsing/test_whitespace.cpp.o

tests/parsing/test_whitespace.i: tests/parsing/test_whitespace.cpp.i
.PHONY : tests/parsing/test_whitespace.i

# target to preprocess a source file
tests/parsing/test_whitespace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhitespaceParsingTest.dir/build.make CMakeFiles/WhitespaceParsingTest.dir/tests/parsing/test_whitespace.cpp.i
.PHONY : tests/parsing/test_whitespace.cpp.i

tests/parsing/test_whitespace.s: tests/parsing/test_whitespace.cpp.s
.PHONY : tests/parsing/test_whitespace.s

# target to generate assembly for a file
tests/parsing/test_whitespace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhitespaceParsingTest.dir/build.make CMakeFiles/WhitespaceParsingTest.dir/tests/parsing/test_whitespace.cpp.s
.PHONY : tests/parsing/test_whitespace.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... IntegerParsingTest"
	@echo "... MipScript"
	@echo "... Parser"
	@echo "... SyntaxTree"
	@echo "... WhitespaceParsingTest"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser/Parser.o"
	@echo "... src/parser/Parser.i"
	@echo "... src/parser/Parser.s"
	@echo "... src/parser/SyntaxNode.o"
	@echo "... src/parser/SyntaxNode.i"
	@echo "... src/parser/SyntaxNode.s"
	@echo "... src/parser/SyntaxTree.o"
	@echo "... src/parser/SyntaxTree.i"
	@echo "... src/parser/SyntaxTree.s"
	@echo "... tests/parsing/test_integers.o"
	@echo "... tests/parsing/test_integers.i"
	@echo "... tests/parsing/test_integers.s"
	@echo "... tests/parsing/test_whitespace.o"
	@echo "... tests/parsing/test_whitespace.i"
	@echo "... tests/parsing/test_whitespace.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

