add_test([=[WhiteSpaceParsing.EmptyString]=]  /Users/gavinhulvey/Documents/GitHub/mipscript/WhitespaceParsingTest [==[--gtest_filter=WhiteSpaceParsing.EmptyString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WhiteSpaceParsing.EmptyString]=]  PROPERTIES WORKING_DIRECTORY /Users/gavinhulvey/Documents/GitHub/mipscript SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Comment.NonIncludedComment]=]  /Users/gavinhulvey/Documents/GitHub/mipscript/WhitespaceParsingTest [==[--gtest_filter=Comment.NonIncludedComment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Comment.NonIncludedComment]=]  PROPERTIES WORKING_DIRECTORY /Users/gavinhulvey/Documents/GitHub/mipscript SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Comment.IncludedComment]=]  /Users/gavinhulvey/Documents/GitHub/mipscript/WhitespaceParsingTest [==[--gtest_filter=Comment.IncludedComment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Comment.IncludedComment]=]  PROPERTIES WORKING_DIRECTORY /Users/gavinhulvey/Documents/GitHub/mipscript SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Comment.IncludedCommentNoSpace]=]  /Users/gavinhulvey/Documents/GitHub/mipscript/WhitespaceParsingTest [==[--gtest_filter=Comment.IncludedCommentNoSpace]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Comment.IncludedCommentNoSpace]=]  PROPERTIES WORKING_DIRECTORY /Users/gavinhulvey/Documents/GitHub/mipscript SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  WhitespaceParsingTest_TESTS WhiteSpaceParsing.EmptyString Comment.NonIncludedComment Comment.IncludedComment Comment.IncludedCommentNoSpace)
