name: Build
on:
  push:
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Install CMake
        run: | 
          sudo apt-get install -y cmake
          cmake --version

      - name: Build the project
        run: |
          mkdir build
          mkdir build/bin
          mkdir build/lib
          cmake --build .

      - name: Test the project
        run: ctest